[package]
name = "websocket_server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tungstenite = "0.20.0"
tokio-tungstenite = "0.20.0"
futures-util = "0.3.0"
